#      _                 _     _
#     | |               | |   (_)
#  ___| |_ __ _ _ __ ___| |__  _ _ __
# / __| __/ _` | '__/ __| '_ \| | '_ \
# \__ \ || (_| | |  \__ \ | | | | |_) |
# |___/\__\__,_|_|  |___/_| |_|_| .__/
#                               | |
#                               |_|

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold #34465c)\
$os\
$username\
[ ](fg:#34465c bg:#4586c4)\
$directory\
[](fg:#4586c4 bg:#34465c)\
$git_branch\
$git_status\
$docker_context\
$c\
${custom.cpp}\
${custom.cs}\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$rust\
$time\
[](fg:#34465c)
[╰─ ](bold #34465c)
"""
command_timeout = 5000

# Replace default symbol in the prompt
[character]
success_symbol = "[](bold #34465c)"

[os]
disabled = false
style = "bg:#34465c"

[os.symbols]
Arch = " "
EndeavourOS = " "

[username]
show_always = true
style_user = "bg:#34465c"
style_root = "bg:#34465c"
format = '[ $user ]($style)'

[directory]
style = "bg:#4586c4"
format = "[$path ]($style)"

[git_branch]
symbol = ""
style = "bg:#34465c"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#34465c"
format = '[$all_status]($style)'

[docker_context]
symbol = ""
style = "bg:#34465c"
format = '[ $symbol $context]($style) $path'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#34465c"
format = '[  $time ]($style)'

# Languages
[c]
symbol = ""
detect_extensions = ['c']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[golang]
symbol = ""
detect_extensions = ['go']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[java]
symbol = ""
detect_extensions = ['java']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[kotlin]
symbol = ""
detect_extensions = ['kt']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[lua]
symbol = "󰢱"
detect_extensions = ['lua']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[nodejs]
symbol = ""
detect_extensions = ['js', 'ts']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[python]
symbol = ""
detect_extensions = ['py']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

[rust]
symbol = "󱘗"
detect_extensions = ['rs']
style = "bg:#34465c"
format = '[ $symbol ($version)]($style)'

# Custom Languages
[custom.cpp]
symbol = ""
command = "echo -n 'v' && echo -n $(cpp --version) | awk '{ print $3 }'"
detect_extensions = ['cpp']
style = "bg:#34465c"
format = '[ $symbol $output]($style)'

[custom.cs]
symbol = "󰌛"
command = "echo -n 'v' && echo -n $(dotnet --version) | awk '{ print $1 }'"
detect_extensions = ['cs']
style = "bg:#34465c"
format = '[ $symbol $output]($style)'

